version: "2.1"
services:
  app:
    build: .
    depends_on:
      db:
        condition: service_healthy
    links:
      - db

  db:
    image: mysql:latest
    restart: always
    ports:
      - "32000:3306"
    environment:
      #MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_ROOT_PASSWORD: strongpassword
    volumes:
      - ./data:/docker-entrypoint-initdb.d/:ro
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 10s
      timeout: 10s
      retries: 10
